export const promoData = [
   {
    id: 1,
    discount: "50%",
    expireDate: "До 15 августа",
    views: 33,
    title: "Пробный сеанс LPG массаж тела+индивидуальная консультация",
    company: {
      name: "Burut Barbershop",
      address: "Садриддина Айни 21/17",
      logo: "/logo@2x.png",
    },
    image: "/images/nails@2x.png",
  },
  {
    id: 2,
    discount: "50%",
    expireDate: "До 15 августа",
    views: 33,
    title: "Пробный сеанс LPG массаж тела+индивидуальная консультация",
    company: {
      name: "Burut Barbershop",
      address: "Садриддина Айни 21/17",
      logo: "/logo@2x.png",
    },
    image: "/images/nails@2x.png",
  },
  {
    id: 3,
    discount: "50%",
    expireDate: "До 15 августа",
    views: 33,
    title: "Пробный сеанс LPG массаж тела+индивидуальная консультация",
    company: {
      name: "Burut Barbershop",
      address: "Садриддина Айни 21/17",
      logo: "/logo@2x.png",
    },
    image: "/images/nails@2x.png",
  },
  {
    id: 4,
    discount: "50%",
    expireDate: "До 15 августа",
    views: 33,
    title: "Пробный сеанс LPG массаж тела+индивидуальная консультация",
    company: {
      name: "Burut Barbershop",
      address: "Садриддина Айни 21/17",
      logo: "/logo@2x.png",
    },
    image: "/images/nails@2x.png",
  },
  {
    id: 5,
    discount: "50%",
    expireDate: "До 15 августа",
    views: 33,
    title: "Пробный сеанс LPG массаж тела+индивидуальная консультация",
    company: {
      name: "Burut Barbershop",
      address: "Садриддина Айни 21/17",
      logo: "/logo@2x.png",
    },
    image: "/images/nails@2x.png",
  },
  {
    id: 6,
    discount: "50%",
    expireDate: "До 15 августа",
    views: 33,
    title: "Пробный сеанс LPG массаж тела+индивидуальная консультация",
    company: {
      name: "Burut Barbershop",
      address: "Садриддина Айни 21/17",
      logo: "/logo@2x.png",
    },
    image: "/images/nails@2x.png",
  },
]
